steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'asia-south1-docker.pkg.dev/analog-delight-467107-p5/fixubuddy-repo/fixubuddy:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/analog-delight-467107-p5/fixubuddy-repo/fixubuddy:$SHORT_SHA'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'fixubuddy-api',
        '--image=asia-south1-docker.pkg.dev/analog-delight-467107-p5/fixubuddy-repo/fixubuddy:$SHORT_SHA',
        '--region=asia-south1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--port=8080'
      ]

images:
  - asia-south1-docker.pkg.dev/analog-delight-467107-p5/fixubuddy-repo/fixubuddy:$SHORT_SHA
